    const mobs = [
        {name:"Allay",type:"Passive",spawn:"Not Natural",mountable:false,dimension:"Overworld",image:"mob/AllayFace.png"},
        {name:"Armadillo",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/ArmadilloFace.png"},
        {name:"Axolotl",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/AxolotlFace.png"},
        {name:"Bat",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/BatFace.png"},
        {name:"Bee",type:"Neutral",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/BeeFace.png"},
        {name:"Blaze",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Nether",image:"mob/BlazeFace.png"},
        {name:"Bogged",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/BoggedFace.png"},
        {name:"Breeze",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/BreezeFace.png"},
        {name:"Camel",type:"Passive",spawn:"Natural",mountable:true,dimension:"Overworld",image:"mob/CamelFace.png"},
        {name:"Cat",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/CatFace.png"},
        {name:"Cave Spider",type:"Neutral",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/Cave_Spider_face.png"},
        {name:"Chicken",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/ChickenFace.png"},
        {name:"Cod",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/CodBody.png"},
        {name:"Copper Golem",type:"Passive",spawn:"Not Natural",mountable:false,dimension:"Overworld",image:"mob/CopperGolemFace.png"},
        {name:"Cow",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/CowFace.png"},
        {name:"Creaking",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/87px-CreakingFace.png"},
        {name:"Creeper",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/CreeperFace.png"},
        {name:"Dolphin",type:"Neutral",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/DolphinFace.png"},
        {name:"Donkey",type:"Passive",spawn:"Natural",mountable:true,dimension:"Overworld",image:"mob/DonkeyFace.png"},
        {name:"Drowned",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/DrownedFace.png"},
        {name:"Elder Guardian",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/Elder_Guardian_face.png"},
        {name:"Ender Dragon",type:"Hostile",spawn:"Not Natural",mountable:false,dimension:"The End",image:"mob/Ender_Dragon_face.png"},
        {name:"Enderman",type:"Neutral",spawn:"Natural",mountable:false,dimension:"Overworld / The End",image:"mob/EndermanFace.png"},
        {name:"Endermite",type:"Hostile",spawn:"Not Natural",mountable:false,dimension:"The End / Overworld",image:"mob/EndermiteFace.png"},
        {name:"Evoker",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/EvokerFace.png"},
        {name:"Fox",type:"Neutral",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/FoxFace.png"},
        {name:"Frog",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/FrogFace.png"},
        {name:"Ghast",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Nether",image:"mob/GhastFace.png"},
        {name:"Giant",type:"Hostile",spawn:"Not Natural",mountable:false,dimension:"Overworld",image:"mob/GiantFace.png"},
        {name:"Glow Squid",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/Glow_Squid_face.png"},
        {name:"Goat",type:"Neutral",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/GoatFace.png"},
        {name:"Guardian",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/GuardianFace.png"},
        {name:"Happy Ghast",type:"Passive",spawn:"Not Natural",mountable:false,dimension:"Nether",image:"mob/Happy_Ghast_face.png"},
        {name:"Herobrine",type:"Hostile",spawn:"Not Natural",mountable:false,dimension:"Overworld",image:"mob/HerobrineFace.png"},
        {name:"Hoglin",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Nether",image:"mob/HoglinFace.png"},
        {name:"Horse",type:"Passive",spawn:"Natural",mountable:true,dimension:"Overworld",image:"mob/HorseFace.png"},
        {name:"Husk",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/HuskFace.png"},
        {name:"Illusioner",type:"Hostile",spawn:"Not Natural",mountable:false,dimension:"Overworld",image:"mob/Illusioner_Face.png"},
        {name:"Iron Golem",type:"Neutral",spawn:"Not Natural",mountable:false,dimension:"Overworld",image:"mob/Iron_Golem_face.png"},
        {name:"Llama",type:"Neutral",spawn:"Natural",mountable:true,dimension:"Overworld",image:"mob/LlamaFace.png"},
        {name:"Magma Cube",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Nether",image:"mob/Magma_Cube_face.png"},
        {name:"Mooshroom",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/MooshroomFace.png"},
        {name:"Mule",type:"Passive",spawn:"Not Natural",mountable:true,dimension:"Overworld",image:"mob/MuleFace.png"},
        {name:"Nautilus",type:"Neutral",spawn:"Not Natural",mountable:true,dimension:"Overworld",image:"mob/NautilusBody.png"},
        {name:"Ocelot",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/OcelotFace.png"},
        {name:"Panda",type:"Neutral",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/PandaFace.png"},
        {name:"Parrot",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/ParrotFace.png"},
        {name:"Phantom",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/PhantomFace.png"},
        {name:"Pig",type:"Passive",spawn:"Natural",mountable:true,dimension:"Overworld",image:"mob/PigFace.png"},
        {name:"Piglin",type:"Neutral",spawn:"Natural",mountable:false,dimension:"Nether",image:"mob/94px-PiglinFace.png"},
        {name:"Piglin Brute",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Nether",image:"mob/94px-Piglin_Brute_face.png"},
        {name:"Pillager",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/PillagerFace.png"},
        {name:"Polar Bear",type:"Neutral",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/Polar_Bear_face.png"},
        {name:"Pufferfish",type:"Neutral",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/PufferfishFace.png"},
        {name:"Rabbit",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/RabbitFace.png"},
        {name:"Ravager",type:"Hostile",spawn:"Not Natural",mountable:true,dimension:"Overworld",image:"mob/RavagerFace.png"},
        {name:"Salmon",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/SalmonBody.png"},
        {name:"Sheep",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/SheepFace.png"},
        {name:"Shulker",type:"Hostile",spawn:"Natural",mountable:false,dimension:"The End",image:"mob/ShulkerFace.png"},
        {name:"Silverfish",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/SilverfishFace.png"},
        {name:"Skeleton",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/SkeletonFace.png"},
        {name:"Skeleton Horse",type:"Passive",spawn:"Not Natural",mountable:true,dimension:"Overworld",image:"mob/Skeleton_Horse_face.png"},
        {name:"Slime",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/SlimeFace.png"},
        {name:"Sniffer",type:"Passive",spawn:"Not Natural",mountable:false,dimension:"Overworld",image:"mob/SnifferFace.png"},
        {name:"Snow Golem",type:"Passive",spawn:"Not Natural",mountable:false,dimension:"Overworld",image:"mob/Snow_Golem_face.png"},
        {name:"Spider",type:"Neutral",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/SpiderFace.png"},
        {name:"Squid",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/SquidFace.png"},
        {name:"Stray",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/StrayFace.png"},
        {name:"Strider",type:"Passive",spawn:"Natural",mountable:true,dimension:"Nether",image:"mob/StriderFace.png"},
        {name:"Tadpole",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/TadpoleFace.png"},
        {name:"Trader Llama",type:"Neutral",spawn:"Not Natural",mountable:true,dimension:"Overworld",image:"mob/Trader_Llama_face.png"},
        {name:"Tropical Fish",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/TropicalFishBody.png"},
        {name:"Turtle",type:"Passive",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/TurtleFace.png"},
        {name:"Vex",type:"Hostile",spawn:"Not Natural",mountable:false,dimension:"Overworld",image:"mob/VexFace.png"},
        {name:"Villager",type:"Passive",spawn:"Not Natural",mountable:false,dimension:"Overworld",image:"mob/VillagerFace.png"},
        {name:"Vindicator",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/VindicatorFace.png"},
        {name:"Wandering Trader",type:"Passive",spawn:"Not Natural",mountable:false,dimension:"Overworld",image:"mob/Wandering_Trader_face.png"},
        {name:"Warden",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/120px-WardenFace.png"},
        {name:"Witch",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/WitchFace.png"},
        {name:"Wither",type:"Hostile",spawn:"Not Natural",mountable:false,dimension:"Overworld / Nether",image:"mob/WitherFace.png"},
        {name:"Wither Skeleton",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Nether",image:"mob/Wither_Skeleton_face.png"},
        {name:"Wolf",type:"Neutral",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/WolfFace.png"},
        {name:"Zoglin",type:"Hostile",spawn:"Not Natural",mountable:false,dimension:"Nether / Overworld",image:"mob/ZoglinFace.png"},
        {name:"Zombie",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/ZombieFace.png"},
        {name:"Zombie Horse",type:"Passive",spawn:"Not Natural",mountable:true,dimension:"Overworld",image:"mob/ZombieHorseFace.png"},
        {name:"Zombie Nautilus",type:"Neutral",spawn:"Not Natural",mountable:true,dimension:"Overworld",image:"mob/ZombieNautilusBody.png"},
        {name:"Zombie Villager",type:"Hostile",spawn:"Natural",mountable:false,dimension:"Overworld",image:"mob/Zombie_Villager_face.png"},
        {name:"Zombified Piglin",type:"Neutral",spawn:"Natural",mountable:false,dimension:"Nether",image:"mob/94px-Zombified_Piglin_face.png"}
    ];